/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HrmRouteImport } from './routes/hrm'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UiKitRouteImport } from './routes/ui-kit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmRoute = HrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/dashboard': typeof DashboardRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/ui-kit': typeof UiKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/dashboard': typeof DashboardRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/ui-kit': typeof UiKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/dashboard': typeof DashboardRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/ui-kit': typeof UiKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/dashboard'
    | '/hrm'
    | '/inventory'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/ui-kit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/dashboard'
    | '/hrm'
    | '/inventory'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/ui-kit'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/dashboard'
    | '/hrm'
    | '/inventory'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/ui-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  DashboardRoute: typeof DashboardRoute
  HrmRoute: typeof HrmRoute
  InventoryRoute: typeof InventoryRoute
  PayrollRoute: typeof PayrollRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UiKitRoute: typeof UiKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrm': {
      id: '/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof HrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  DashboardRoute: DashboardRoute,
  HrmRoute: HrmRoute,
  InventoryRoute: InventoryRoute,
  PayrollRoute: PayrollRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UiKitRoute: UiKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
